### ISSUE TITLE
Part III D: Purely national exclusion grounds

### ISSUE THREAD

**Issue by sakispantazis** [ESPD/ESPD-Service#102]
Although this has been mentioned/requested already and indirectly in the form of a comment regarding issue #86, we would like to stress out that economic operators would also welcome the direct description of national grounds in the ESPD. 
Is it possible to include the relevant box providing the space for contracting authorities to describe such grounds in the ESPD service? 
I completely understand that linking it with e-Certis to retrieve this info would be by far the best solution, compared to the "quick and dirty" solution of adding a text box,  (i.e. this has been your answer on this question during the eSender Annual Seminar 2016). However, if you working on this issue already, when should we expect this to be solved (release?)

**Comment by ec-mcs** [comment]
Version 2 of the ESPD data model allows for the direct mentioning of the national exclusion grounds. Already now it is possible in our ESPD service to show the criteria from eCertis. Therefore I will close this issue.
