### ISSUE TITLE
Print View - Part IV section a.

### ISSUE THREAD

**Issue by sakispantazis** [ESPD/ESPD-Service#103]
Obviously contracting authorities omit answering section “a. Global indication for all selection criteria” if they want specific selection criteria (sections “A”, “B”,”C”,”D”) of Part IV. However, in this case, although section a. does not appear to the economic operators when they fill out the form, **in the print view** the section a of Part IV is present, and neither “yes” nor “no” have been selected,  confusing the economic operators.

**Comment by hildekjol** [comment]
We have also received feedback from users that this is confusing. Today we even had a CA that wanted to reject EOs that had not answered this question, even though it was not possible for the EOs to answer it. We had some worried EOs on the phone.

When will it be fixed?

**Comment by hildekjol** [comment]
Some more information on this issue: CA has ticked off for IV a + IV A-D (the top question), see "espd-request" as xml and pdf. In the pdf you can see both IV a and IV A-D. But when the xml is read into the ESPD-service, only IV a will be shown to the EO. The pdf created by the EO will also just show IV a. See "espd-response".

We have had quite a few emails and calls on this issue.

Suggested solution: When CA ticks off for IV a, the ESPD-service hides IV A-D making it impossible to tick off both. Then you (hopefully) will not have the case of the xml and the pdf being different.
[espd-request.zip](https://github.com/ESPD/ESPD-Service/files/850081/espd-request.zip)
[espd-response.zip](https://github.com/ESPD/ESPD-Service/files/850082/espd-response.zip)

**Comment by ec-mcs** [comment]
It is planned to solve this in our March release. Hilde the approach you suggest is good. There would be another approach as well: The CA could select if they want to use the alpha criterion (YES/NO). Depending on the answer alpha or A to D are shown. What do you think?

**Comment by hildekjol** [comment]
Sure, that would work as well. The same logic, but maye easier to implement.

**Comment by ec-mcs** [comment]
The text above the alpha criterion should be:
"Do you want to use the selection criteria from A to D: Yes/No"
If yes: A to D are shown, not alpha
If no: Alpha criterion is shown, not A/B/C/D
Default is: Yes

**Comment by hildekjol** [comment]
Agree that default should be YES to A-D. We are encouraging our users to use A-D, not Alpha.
