### ISSUE TITLE
Translation of starting page in German is not yet completed

### ISSUE THREAD

**Issue by RolfKewitz** [ESPD/ESPD-Service#104]
In ESPD service web pages there is text which has not been translated into German:
(see https://ec.europa.eu/tools/espd/filter?lang=de)

On starting page:
1) "Create response" should be translated
2) Helping information for "Zwei EEE zusammenführen" should be translated
3) "Where is your buisness located" should be translated.

See Screenshot:
![espd_partially_wrong_language](https://cloud.githubusercontent.com/assets/23098260/19767586/d91af99e-9c53-11e6-9734-bc9a4ff172e7.jpg)

**Comment by ojlaranjo** [comment]
Issues 1 and 2 still not translated.
Issue 3 translated merely in ESPD test environment.

**Comment by ojlaranjo** [comment]
Everything has been correctly translated in DEV.
