### ISSUE TITLE
Printing Alpha Criterion display issue when the user is an Economic Operator

### ISSUE THREAD

**Issue by ojlaranjo** [ESPD/ESPD-Service#105]
When filling in the ESPD online as an economic operator everything is fine – a: Global indication for all selection criteria is hidden and I am forced to fill in information for each and every selection criteria (picture 1). 
![1](https://cloud.githubusercontent.com/assets/22073365/19965303/a97e98f8-a1c6-11e6-86de-ddd9e82abb4c.jpg)

However, when finishing the ESPD and printing it I realize that the printed version looks different (picture 2). Now a: Global indication for all selection criteria appears contrary to when I filled in information online. 
![2](https://cloud.githubusercontent.com/assets/22073365/19965310/afe11bf8-a1c6-11e6-861f-21fa7a652e58.jpg)

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on DEV
