### ISSUE TITLE
RO language: country list

### ISSUE THREAD

**Issue by tsirafa** [ESPD/ESPD-Service#107]
Dear Sirs,

We are involved in a tender process where ESPD is required to be filled in in in Romanian language.

1.	The Country list has nothing to do with Romanian language but most probably with Spanish language.
As this may affect the applicability of the ESPD to this tender can you please verify that the Romanian version of ESPD page 
loads the country names in Romanian language?

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on DEV
