### ISSUE TITLE
Information electronically available with added text

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#109]
From a feedback from Spain about the ESPD we have received the following comment:
"Additionally when the ESPD standard form (in several points) asks for
the access information it would be clarifying that, in accordance with
Article 59.1, paragraph 5 and 59.5 of Directive 2014/24/EU, it adds:
“when it is an EU Member State’s database free of charge”."

![capture](https://cloud.githubusercontent.com/assets/20335285/20256526/6e508d1e-aa44-11e6-8406-8f12f3c20eb7.PNG)

We should change the text from 
"Is this information available electronically?"

To
"Is this information freely available electronically from an EU Member State database?"

**Comment by dariuszwojcicki** [comment]
Needs to be translatated and is used in different places of the application.

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on dev
