### ISSUE TITLE
Embed XML into PDF to help users 

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#110]
To help users we should provide the possiblity to embed and retrieve the XML from the PDF. If possible we should use Apache™ FOP: "Embedding"

**Comment by ec-mcs** [comment]
Is linked to and can be closed
https://github.com/ESPD/ESPD-Service/issues/122

**Comment by dg-grow-virgiliu-ratoi** [comment]
We will not implement XML embedding into PDF, instead we will generate a ZIP archive containing the two formats.
