### ISSUE TITLE
piwik statistics understated

### ISSUE THREAD

**Issue by dg-grow-alexey-lukashov** [ESPD/ESPD-Service#112]
ESPD url https://ec.europa.eu/growth/tools-databases/espd/ is not included into common statistics

we need to mix together statistics for both ESPD urls:
-	https://ec.europa.eu/growth/tools-databases/espd/
-	https://ec.europa.eu/tools/espd/

**Comment by dg-grow-virgiliu-ratoi** [comment]
Also this link: [https://ec.europa.eu/espd](https://ec.europa.eu/espd)
