### ISSUE TITLE
The data coming from eCertis is not shown

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [ESPD/ESPD-Service#114]
In version 2016.10.01, when clicking on a criterion (as a CA) the data coming from the eCerits application is not shown, even though the response coming from eCertis seems not be empty.

**Comment by lauramrtn** [comment]
I also noticed that the eCertis information is shown for some countries i.e. Italy but is not shown for others e.g. UK. 

Also, is there anywhere which illustrates the fields that are pulled through into the ESPD service from eCertis? I just want to ensure that our policy team are clear when updating eCertis.

**Comment by ec-mcs** [comment]
Indeed data from IT is shown but not from UK. Possible to still fix this in December?
