### ISSUE TITLE
Google Chrome cuts of in some cases the ESPD

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#116]
We have the case that sometimes Google Chrome cuts off the ESPD. This seems to be an issue inside Chrome. We should collect information about this issue to identify a pattern that helps us to understand the source of the problem and provide an alternative to users if necessary. With my office computer it does not work
Chrome: Version 54.0.2840.99 m

**Comment by dariuszwojcicki** [comment]
Chrome: Version 53.0.2785.143 m
Checked for different language versions (Polish, German).
