### ISSUE TITLE
EN text about "guilty of misinterpretation" is wrong

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#117]
**Currently**
Guilty of misinterpretation, withheld information, unable to provide required documents and obtained confidential information of this procedure
Can the economic operator confirm that:

a) It has not been guilty of serious misrepresentation in supplying the information required for the verification of the absence of grounds for exclusion or the fulfilment of the selection criteria,

b) It has not withheld such information,

c) It has been able, without delay, to submit the supporting documents required by a contracting authority or contracting entity, and

d) It has not undertaken to unduly influence the decision making process of the contracting authority or contracting entity, to obtain confidential information that may confer upon it undue advantages in the procurement procedure or to negligently provide misleading information that may have a material influence on decisions concerning exclusion, selection or award?

**Correct - the answers have to be changed**

a) It has ~~not~~ been guilty of serious misrepresentation in supplying the information required for the verification of the absence of grounds for exclusion or the fulfilment of the selection criteria,

b) It has ~~not~~ withheld such information,

c) It has **not** been able, without delay, to submit the supporting documents required by a contracting authority or contracting entity, and

d) It has ~~not~~ undertaken to unduly influence the decision making process of the contracting authority or contracting entity, to obtain confidential information that may confer upon it undue advantages in the procurement procedure or to negligently provide misleading information that may have a material influence on decisions concerning exclusion, selection or award?

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on ACC
