### ISSUE TITLE
Review the generation of XML files and print workflow

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [ESPD/ESPD-Service#122]
We will adjust our solution to show "Next" on the Finish page. And once the user will click "Next" they will see the overview and below we will show "Save as PDF" | "Save as XML" | "Save". The save buttons would be configurable like
- saveAsXML = True/False
- saveAsPDF = True/False
- save = True/False (this option would save first the XML and then PDF)
- saveAsZIP = True/False (will save both files in Zip)

**Comment by ec-mcs** [comment]
good idea:
Timo Rantanen / Hansel / Finland: in the zip could you alko provide txt file with instructions... go to www.... for filling in the XMl

**Comment by ec-mcs** [comment]
Timo Rantanen / Hansel / Finland: in the zip could you alko provide txt file with instructions... go to www.... for filling in the XMl

Timo Rantanen / Hansel / Finland: also

Laura Martin: Zip file sounds good with both types.  Also a 'read me' file would be welcome by users I think.

**Comment by nfouka** [comment]
Hello , 
I would like to save the Type of procedure but I can not find it on the XML file, could you tell me how to interger it in the **XML** file?
does the EspdDocument.getTypeProdecure return a non-null value?
