### ISSUE TITLE
Translation error in several languages (EN, FI, PL) Part III.B

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#125]
Part III.B

There is a discrepancy between the text of ESPD regulation and the text in ESPD service. 

The regulation states: 
"Has the economic operator **met all its obligations** relating to the payment of taxes or social security contributions, both in the country in which it is established and in Member State of the contracting authority or contracting entity if other than the country of establishment?""

But the ESPD service states:

"Has the economic operator **breached its obligations** relating to the payment of taxes, both in the country in which it is established and in Member State of the contracting authority or contracting entity if other than the country of establishment? "

AND

"Has the economic operator **breached its obligations** relating to the payment social security contributions, both in the country in which it is established and in Member State of the contracting authority or contracting entity if other than the country of establishment? "

Breaching its obligations and meeting them are two different things.

**Correction:**

**"breached its obligations"** should be replaced with **"met all its obligations"**

This also exists at least in Polish and Finnish:

I can only comment the Finnish translation... Polish is gibrish to me:

FINNISH ESPD SERVICE TEXT:

INSTEAD OF

"Verojen maksu
Onko talouden toimija **rikkonut** verojen maksamiseen liittyviä velvoitteitaan sekä maassa, johon toimija on sijoittautunut, että hankintaviranomaisen tai -yksikön jäsenvaltiossa, jos se on muu kuin sijoittautumismaa? "

THE TEXT SHOUD READ AS FOLLOWS:

"Onko talouden toimija **täyttänyt kaikki** verojen maksamiseen liittyvät velvoitteensa sekä maassa, johon toimija on sijoittautunut, että hankintaviranomaisen tai  yksikön jäsenvaltiossa, jos se on muu kuin sijoittautumismaa?"

AND

INSTEAD OF 

"Sosiaaliturvamaksujen maksaminen
Onko talouden toimija **rikkonut** sosiaaliturvamaksujen maksamiseen liittyviä velvoitteitaan sekä maassa, johon toimija on sijoittautunut, että hankintaviranomaisen tai -yksikön jäsenvaltiossa, jos se on muu kuin sijoittautumismaa? "

THE TEXT SHOUD READ AS FOLLOWS:

"Onko talouden toimija **täyttänyt kaikki** sosiaaliturvamaksujen maksamiseen liittyvät velvoitteensa sekä maassa, johon toimija on sijoittautunut, että hankintaviranomaisen tai  yksikön jäsenvaltiossa, jos se on muu kuin sijoittautumismaa?

**Comment by ec-mcs** [comment]
This is intentional. The questions in the exclusion grounds are phrased in a way that the EO has to say "No" to say he is "ok"

- Do you take medication?
- Do you drink more than one glass of alcohol per day?
- Have you been in the hospital in the last 6 months?
- Are you bankrupt?
- Have you breached the obligation to pay taxes?

Answering sometimes YES and sometimes NO is not user friendly...

Hope this explains it. If the answer is ok for you, please feel free to close this issue

s?
