### ISSUE TITLE
Just a Q?

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#130]
What has happened to section V in ESPD Service? Whatever I select I do not seem to get Section V anymore in view.... (comment related to version: Last Update: 2016-12-19 13:36)

**Comment by ec-mcs** [comment]
This is actually the wanted behavior. Only the CA will not see part V as they are not able to provide any information there and it created a lot of confusion. If ok for we can close this issue.

**Comment by rantati7** [comment]
Hmmn… let’s discuss / need to check if in fact there’s nothing for the CA. I haven’t given it a thorough thought

Timo Rantanen

Hansel Oy
PL 1386, 00101 Helsinki
(Mannerheiminaukio 1 A)
Matkapuhelin 0294 444 250
timo.rantanen@hansel.fi<mailto:timo.rantanen@hansel.fi>
www.hansel.fi<http://www.hansel.fi/>

Teemme yhdessä onnistuneita hankintoja.

Lähettäjä: Marc Christopher Schmidt [mailto:notifications@github.com]
Lähetetty: 2. tammikuuta 2017 15:21
Vastaanottaja: ESPD/ESPD-Service <ESPD-Service@noreply.github.com>
Kopio: Rantanen Timo <Timo.Rantanen@hansel.fi>; Author <author@noreply.github.com>
Aihe: Re: [ESPD/ESPD-Service] Just a Q? (#130)


This is actually the wanted behavior. Only the CA will not see part V as they are not able to provide any information there and it created a lot of confusion. If ok for we can close this issue.

**Comment by rantati7** [comment]
It is ok to close the issue here. 

For 1.1 this is the part where the long discussed "points" giving comes in play.
