### ISSUE TITLE
Incorrect URL in D: Purely national exclusion grounds

### ISSUE THREAD

**Issue by dariuszwojcicki** [ESPD/ESPD-Service#132]
"Purely national exclusion grounds" should not have any link to ECERTIS from EO Vies. This link should be disabled like we have it for CA View. 
![20170116 2 bug](https://cloud.githubusercontent.com/assets/22236761/21984401/feca5fae-dbf5-11e6-80c2-01ad4a501873.png)

**Comment by ec-mcs** [comment]
Actually national exclusion grounds should be shown as well for CAs (country from CA) as for EOs (country of EO)

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on dev
