### ISSUE TITLE
Consortium name should be a criterion requirement

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [ESPD/ESPD-Service#135]
In Part II - C: Information about reliance on the capacities of other entities, the field 'Consortium' must be a requirement under the criterion "0d62c6ed-f074-4fcf-8e9f-f691351d52ad".

**Comment by dg-grow-virgiliu-ratoi** [comment]
Originally defined on the Data Model here: [https://github.com/ESPD/ESPD-EDM/issues/52](https://github.com/ESPD/ESPD-EDM/issues/52)

**Comment by ec-mcs** [comment]
Not valid anymore

**Comment by dariuszwojcicki** [comment]
We should not store/retrive the consortium name in XML any more.
