### ISSUE TITLE
Set up of economic operator has only 5 years... should be (much) more

### ISSUE THREAD

**Issue by tsirafa** [ESPD/ESPD-Service#14]
The EO can select only the last 5 years for the criterion "Set up of economic operator". This is actually wrong. Let's have a "year" field where someone can enter YYYY. And it cannot be more than this year (>current year)

**Comment by dariuszwojcicki** [comment]
Due to effort (the static filed should be converted into dynamic) needed to change it is reasigned to next release (from 2016.09).

**Comment by dg-grow-virgiliu-ratoi** [comment]
We will replace the dropdown with a textbox for all fields representing a year.

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on "development" branch
