### ISSUE TITLE
Set up of economic operator, not saving

### ISSUE THREAD

**Issue by AndreasBom** [ESPD/ESPD-Service#145]
The 'please specify'-field in section 'Selection' --> 'Set up of economic operator' don't save to xml. It is showing in the preview pdf, but the data is not saved in the xml.    
pic 1) creating new ESPD.    
pic 2) generated preview pdf   
pic 3) importing saved xml   
pic 4) xml   
    
![espd1](https://cloud.githubusercontent.com/assets/10333113/22500942/d69ea44a-e866-11e6-9629-a2479fb5a79d.jpeg)

![espd2](https://cloud.githubusercontent.com/assets/10333113/22501010/219b56b4-e867-11e6-9205-71748ba5a4c1.jpeg)

![espd4](https://cloud.githubusercontent.com/assets/10333113/22501028/29c9c014-e867-11e6-860f-b971a10ca245.jpeg)

![espdpdf](https://cloud.githubusercontent.com/assets/10333113/22501033/2cfcc330-e867-11e6-974d-873760a20b78.jpeg)

**Comment by dg-grow-virgiliu-ratoi** [comment]
Thanks for reporting this, I think it was introduced with release 2016.12.01 on the 18th of January. It was supposed to fix the issue #14
