### ISSUE TITLE
An ESPD in PDF format contains unreadable text

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [ESPD/ESPD-Service#147]
For certain countries (e.g. Norway) the generated ESPD in PDF format does not display certain long texts in a readable way.

**Comment by dg-grow-virgiliu-ratoi** [comment]
Reducing the zoom level of the Overview page and refreshing it should be a possible workaround.

**Comment by dg-grow-virgiliu-ratoi** [comment]
The issue is related to the display of certain <p> elements, e.g in the case of 'Guilty of misinterpretation'. The source of the problem comes from the **xhtml2fo.xsl** file which specifies the _<xsl:attribute-set name="p">_ element. We need to reduce the **space-before** and **space-after** attribute values.

**Comment by hildekjol** [comment]
Is this issue fixed just now - in connection with the update, perhaps? I can't seem to reproduce the error.

**Comment by dg-grow-virgiliu-ratoi** [comment]
it should have been fixed with version 2017.02 released on the 1st of March.
