### ISSUE TITLE
Able to add multiple references in selection criteria

### ISSUE THREAD

**Issue by tsirafa** [ESPD/ESPD-Service#15]
There is a limitation in the eESPD of 5 concerning the list of works/deliveries/services performed during the reference period. Is it possible to remove this limitation so that the EO can addi new works/deliveries/services as many times as needed?
We need to allow EO to add as many references they like to have.

**Comment by ec-mcs** [comment]
![capture](https://cloud.githubusercontent.com/assets/20335285/17730381/c688950c-6468-11e6-82eb-3d32fac90ef8.PNG)

**Comment by dg-grow-virgiliu-ratoi** [comment]
Financial ratios should also have multiple references.

**Comment by dg-grow-alexey-lukashov** [comment]
-Financial ratios should also have multiple references.
-For works contracts: performance of works of the specified type 
-For supply contracts: performance of deliveries of the specified type 
-For service contracts: performance of services of the specified type

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on branch "feature-multiple-references"
