### ISSUE TITLE
Update remaining translations from the December 2016 version of the application

### ISSUE THREAD

**Issue by dariuszwojcicki** [ESPD/ESPD-Service#150]
[translations.zip](https://github.com/ESPD/ESPD-Service/files/788046/translations.zip)

**Comment by dg-grow-alexey-lukashov** [comment]
done on dev (except NO)

**Comment by hildekjol** [comment]
Please find part of the Norwegian translation file, as requested from Marc-Cristopher Schmidt.
**Please note** that we have added some fields into the excel sheet. These are serious translation errors that need a quick fix. The fields are marked pink at the bottom of the list.
[20170227_espd_translation_NO.xlsx](https://github.com/ESPD/ESPD-Service/files/806224/20170227_espd_translation_NO.xlsx)

**Comment by MaritThomsen** [comment]
Where can I find an updated version of the translations in all countries?
Thanks in advance

**Comment by MaritThomsen** [comment]
The zip file with translations is from 20/2-2017, but NO labels were added in a comment on 28/2-2017. Is i possible to get an updated zip with all translations including NO?
