### ISSUE TITLE
Beautify how information from eCertis is presented

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#152]
![capture](https://cloud.githubusercontent.com/assets/20335285/23608248/cbadeb6a-0268-11e7-9dfa-c1a1284a6e6e.PNG)

Under the question
* Law (article)
* Description
* Evidence (s)

**Comment by dg-grow-virgiliu-ratoi** [comment]
Also, this issue could be relevant: [https://github.com/ESPD/ESPD-EDM/issues/43](https://github.com/ESPD/ESPD-EDM/issues/43)

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on dev
