### ISSUE TITLE
Part III:D National exclusion grounds - Response print view displays III D even when it is not ticked off in the ESPD-request

### ISSUE THREAD

**Issue by hildekjol** [ESPD/ESPD-Service#155]
When CA does not tick off on part III D National exclusion grounds, the field does not show for EO when he fills out the ESPD-request. But when the ESPD-response is printed to PDF, it displays the question from III D, leaving it un-answered. See the picture.

We have gotten some questions from both EOs and CAs on this issue.

![image](https://cloud.githubusercontent.com/assets/3802356/24395039/764c0c8c-139e-11e7-8ba7-75bbc179bd0f.png)
[Prosedyrereglene Bilag 5 Det europeiske egenerklæringsskjemaet.zip](https://github.com/ESPD/ESPD-Service/files/874889/Prosedyrereglene.Bilag.5.Det.europeiske.egenerklaeringsskjemaet.zip)

**Comment by ec-mcs** [comment]
Works now:
CA does not check III d export ESPD. 
EO imports ESPD request: III d does not show up
EO exports ESPD response
CA reviews ESPD response III d does not show up.
I will close this issue now.
