### ISSUE TITLE
Expand Part II about SMEs - tick off box for micro, small and medium-sized enterprises

### ISSUE THREAD

**Issue by hildekjol** [ESPD/ESPD-Service#156]
Would it be possible to expand Part II about SMEs to distinguish between micro, small and medium-sized enterprises? If the answer is YES, then the tick off boxes will show. See picture.
The reason: Better statistics. There are political requirements to better understand the different SME categories.
![smes](https://cloud.githubusercontent.com/assets/3802356/24697018/e28fb120-19eb-11e7-8466-16da03ae685f.JPG)

**Comment by ec-mcs** [comment]
I will close it here as it is more about the data model
