### ISSUE TITLE
Java version 8

### ISSUE THREAD

**Issue by klakegg** [ESPD/ESPD-Service#158]
Hi,

When are you planning to stop supporting Java 7? Java 7 has not been supported by Oracle the last two years, and  Java 9 is expected this summer.

**Comment by dg-grow-virgiliu-ratoi** [comment]
That's a good question, we are using Java 7 because when the project was started the environment was created with JDK 7.  It will take some time though until the Java 8 environments are set up and everything is tested.

**Comment by ec-mcs** [comment]
As this does not affect the use of the application and due to the phase-out, we will not update our service to Java 8 (or a newer version).
