### ISSUE TITLE
translation Danish 

### ISSUE THREAD

**Issue by dariuszwojcicki** [ESPD/ESPD-Service#168]
Please find below a mistake on the translation for the Danish : 

Misleading explanation in Part IV C Technical Assistance - Annual average number of employees.

According to the screen dump below, the explanation for "Annual average number of employees" indicates that the applicant must fill in the number of employed as well as the number of senior executives.
The last part of the explanation "and the number of senior employees" should be deleted. Information about the number of senior executives is selected in an independent point, see the screen dump.

The current wording gives confusion to the applicants, as the explanation asks for two numbers but only one field to be typed in.

**Comment by ec-mcs** [comment]
I think it is implemented correctly as it is now...
