### ISSUE TITLE
Change in NO translation

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#174]
Hi MC

For our response on the changes in the service, see mail there will be a separate mail (probably from Hilde – we are working on it now)
But we have some translation needs……

We have got an issue concerning the translation from our Ministry. Could you please delete in the Norwegian translation the part we have highlighted below?

createcafinish_concl_statements_text=Undertegnede erklærer at opplysningene angitt i del II-IV ovenfor er nøyaktige og korrekte, og at de har blitt avgitt i fullt kjennskap til konsekvensene av å oppgi uriktige opplysninger.<p>Undertegnede bekrefte å kunne fremlegge attester og andre former for dokumentasjon som det henvises til, straks og på anmodning unntatt når:</p><p>a) oppdragsgiver har mulighet til å innhente de relevante støttedokumentene kostnadsfritt i en database i en EØS-stat, hvis denne stilles gratis til rådighet, eller</p><p>b) oppdragsgiver allerede ~~senest den 18. april 2018~~ er i besittelse av de aktuelle dokumentene.</p><p>Undertegnede gir [vennligst angi oppdragsgiveren angitt i del I, avsnitt A] adgang til dokumentasjon til støtte for de opplysninger som har blitt avgitt i [vennligst angi den relevante del, det relevante avsnitt, det eller de relevante punkter] i dette europeiske egenerklæringsskjemaet med sikte på [angi konkurransen: (kort beskrivelse, henvisning til Den Europæiske Unions Tidende, referanseenummer)].</p>

Furthermore we´ve got a lot o fuser feedback on one of the buttons at the last page.  Could you please put in a new text there as well:
Existing text: print=Skriv ut
New tekst:  print=Last ned

**Comment by ec-mcs** [comment]
Two changes in the NO translations
**FIRST CHANGE**
createcafinish_concl_statements_text=Undertegnede erklærer at opplysningene angitt i del II-IV ovenfor er nøyaktige og korrekte, og at de har blitt avgitt i fullt kjennskap til konsekvensene av å oppgi uriktige opplysninger.<p>Undertegnede bekrefte å kunne fremlegge attester og andre former for dokumentasjon som det henvises til, straks og på anmodning unntatt når:</p><p>a) oppdragsgiver har mulighet til å innhente de relevante støttedokumentene kostnadsfritt i en database i en EØS-stat, hvis denne stilles gratis til rådighet, eller</p><p>b) oppdragsgiver allerede senest den 18. april 2018 er i besittelse av de aktuelle dokumentene.</p><p>Undertegnede gir [vennligst angi oppdragsgiveren angitt i del I, avsnitt A] adgang til dokumentasjon til støtte for de opplysninger som har blitt avgitt i [vennligst angi den relevante del, det relevante avsnitt, det eller de relevante punkter] i dette europeiske egenerklæringsskjemaet med sikte på [angi konkurransen: (kort beskrivelse, henvisning til Den Europæiske Unions Tidende, referanseenummer)].</p>
**TO**
createcafinish_concl_statements_text=Undertegnede erklærer at opplysningene angitt i del II-IV ovenfor er nøyaktige og korrekte, og at de har blitt avgitt i fullt kjennskap til konsekvensene av å oppgi uriktige opplysninger.<p>Undertegnede bekrefte å kunne fremlegge attester og andre former for dokumentasjon som det henvises til, straks og på anmodning unntatt når:</p><p>a) oppdragsgiver har mulighet til å innhente de relevante støttedokumentene kostnadsfritt i en database i en EØS-stat, hvis denne stilles gratis til rådighet, eller</p><p>b) oppdragsgiver allerede er i besittelse av de aktuelle dokumentene.</p><p>Undertegnede gir [vennligst angi oppdragsgiveren angitt i del I, avsnitt A] adgang til dokumentasjon til støtte for de opplysninger som har blitt avgitt i [vennligst angi den relevante del, det relevante avsnitt, det eller de relevante punkter] i dette europeiske egenerklæringsskjemaet med sikte på [angi konkurransen: (kort beskrivelse, henvisning til Den Europæiske Unions Tidende, referanseenummer)].</p>

**SECOND CHANGE**
print=Skriv ut
**TO**
print=Last ned

**Comment by VibekeE** [comment]
This looks fine

**Comment by hildekjol** [comment]
Could you also update the field crit_eu_text_purely_national?

**THIRD CHANGE**
crit_eu_text_purely_national=Huk av dersom det er angitt nasjonale avvisningsgrunner i kunngjøringen eller i anskaffelsesdokumentene
**TO**
crit_eu_text_purely_national=Oppdragsgiver: Huk av for at det foreligger nasjonale avvisningsgrunner.
Leverandører: Besvar om det er forhold ved deg som leverandør som gjør at en eller flere av de nasjonale avvisningsgrunnene gjelder for din virksomhet?

**Comment by ec-mcs** [comment]
Implemented
