### ISSUE TITLE
Update the TED URL

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [ESPD/ESPD-Service#177]
Update the URL used in the communication with the Publication Office for retrieving the information about the procurement procedure

**Comment by MarianUVO** [comment]
Hallo, we have troule to contact api, with autentication  api/"detaultPasswordInCode" .
{
    "timestamp": "2017-06-28T09:09:14Z",
    "status": 401,
    "error": "Unauthorized",
    "message": "Bad credentials",
    "path": "/api/tedapi/latest/notice"
}

**Comment by dg-grow-virgiliu-ratoi** [comment]
You can disable this functionality by setting the following property to null.

`# The base URL of the TED contract notice REST service. Can be omitted to disable the TED integration.
ted.api.base.url=`

**Comment by MarianUVO** [comment]
Our integration require this service. How is possible to use this service from ESPD app ?

**Comment by dg-grow-virgiliu-ratoi** [comment]
In that case you need to contact the Publications Office to get the proper credentials.

**Comment by ec-mcs** [comment]
If you are an eSender, could you try to use those credentials? I don't know if this will work but it is worth trying.

**Comment by MarianUVO** [comment]
We tryied to use a eSender credentials of our partner . Response is NEGATIVE. 
{
    "timestamp": "2017-06-28T14:19:05Z",
    "status": 401,
    "error": "Unauthorized",
    "message": "Bad credentials",
    "path": "/api/tedapi/latest/notice/244333-2017"
}

We are integrating ESPD app .  Integration with TED does not work.
Can you generate for us new credentials for production API call to read data from TED?

**Comment by dg-grow-virgiliu-ratoi** [comment]
Unfortunately, we don't generate the credentials ourselves. You should contact your partner or the Publications Office about the credentials.

**Comment by MarianUVO** [comment]
Thank ou for answer, we contacted our PM office .
