### ISSUE TITLE
WINDOWS 10 - IE - ICON box is empty

### ISSUE THREAD

**Issue by dariuszwojcicki** [ESPD/ESPD-Service#187]
In the Part III, Exclusion grounds - In the first section - Your answer ?the icon + and Bin is missing.

Please see the print screen.
[Empty icon box.docx](https://github.com/ESPD/ESPD-Service/files/1156178/Empty.icon.box.docx)

based on
https://webgate.ec.europa.eu/CITnet/jira/projects/ECERTIS/issues/ECERTIS-413

**Comment by ec-mcs** [comment]
As this does not affect the use of the application and due to the phase-out, we will not correct this.
