### ISSUE TITLE
WINDOWS10 - IE - Arrow next to the section title not displayed

### ISSUE THREAD

**Issue by dariuszwojcicki** [ESPD/ESPD-Service#188]
Next to each section there is a small arrow to hide or display the section.

See print screen atttached with the good example from EDGE and the issue example from IE.

[ESPD issue.docx](https://github.com/ESPD/ESPD-Service/files/1156190/ESPD.issue.docx)
based on
https://webgate.ec.europa.eu/CITnet/jira/browse/ESPD-133

**Comment by ec-mcs** [comment]
As this does not affect the use of the application and due to the phase-out, we will not correct this.
