### ISSUE TITLE
Tooltip Arrow layout

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#19]
At the tooltips on page 2 (page of "Welcome to the UEA-Service") the arrow is not always in the right place of the text balloon. (See Annex: 'Tooltip
![tooltip](https://cloud.githubusercontent.com/assets/19528809/17187190/863a2a0a-5438-11e6-8eaa-d6b289470433.jpg)
.jpg ")

**Comment by ec-mcs** [comment]
We will close it as we will phase-out our solution and it does not effect the usage really.
