### ISSUE TITLE
Updated Norwegian translation file

### ISSUE THREAD

**Issue by hildekjol** [ESPD/ESPD-Service#196]
From e-mail til Dariusz on Sept. 11, 2017:
I have updated the Norwegian language file and even made a pull request, but I suppose I haven’t got a write access to the ESPD-Service repository. Take a look at https://github.com/ESPD/ESPD-Service/pull/191 , my user is hildekjol and the account is connected to my gmail-address, not my Difi-address. Could you look through the pull request and merge it if it looks OK? Thanks.

Another thing, I noticed that in the ESPD service, there is a field for “Type of procedure”, but I couldn’t find the correct place for it in the language file. The Norwegian translation, based on the fields in the ESPD service should be as follows:
Type of procedure -> Type prosedyre
Open procedure -> Åpen anbudskonkurranse
Restricted procedure -> Begrenset anbudskonkurranse
Competitive procedure with negotiation -> Konkurranse med forhandling
Competitive dialogue -> Konkurransepreget dialog
Innovation partnership -> Konkurranse om innovasjonspartnerskap

**Comment by dg-grow-virgiliu-ratoi** [comment]
there is an additional value that we need to translate. what is the translation for 'Not specified'?
