### ISSUE TITLE
Freetext elements vs codelists

### ISSUE THREAD

**Issue by JoseLuisCueva** [ESPD/ESPD-Service#2]
Several elements in the Response are treated as unconstrained text (obviously in the language of the E.O.). This raises interoperability (and perhaps legal certainty) issues, in particular for en electronic document meant for electronic procurement in a multilingual realm.
It might be solved (at least in many important cases) by using codelists properly maintained. 
In some cases there are already well-known classifications, taxonomies or codelists, defined and maintained by the EC itself (eg CPV for defining the "business area covered by the contract"), by international organizations such as the International Labour Organization (eg  ISCO for classification of occupations) or the UN (eg UN/SPSC), or by Standards Bodies. These might be supplemented by properly maintained and referenced public lists, even provided by the country of the Contracting Authority.
I believe the ESPD EDM and the ESPD service should provide the capability for using and referencing codelists like these, so both the E.O. and the C.A. (and eventually their IT systems) can make sure both parties understand unambiguously (in the common language provided by the codelist or taxonomy) the same thing in the ESPD Request (or Contract notice) and in the ESPD Response.

**Comment by JoseLuisCueva** [comment]
Example 1: yearly/average yearly turnover "in the business area covered by the contract andspecified in the relevant notice or the procurement documents..."
The "standard form" does not provide a place for the E.O. to state the business area his turnover is computed for. But even with a place for a description in natural language there is a problem for matching what the C.A. meant in his Request or CN or CD´s (in the C.A. language) and what the E.O. is expressing in his ESPD Response (in his own language).
Taxonomies such as the CPV (EC Resolution) or UN/SPSC could serve as a way for solving this issue.

**Comment by JoseLuisCueva** [comment]
Example 2: Part IV-C "TECHNICAL AND PROFESSIONAL ABILITY", several items for employees and staff qualifications.
In this case, the use of taxonomies such as the International Standard Classification of Occupations (ISCO-08) from the International Labour Organization (ILO) could seve as an interoperable, neutral  and unambiguous way of expressing the professional qualifications of employees, staff, etc.

**Comment by paulakeen** [comment]
I would recommend to assess the use of ESCO, the European Skills, Competences, Qualifications and Occupations taxonomy defined and maintained by COM (DG EMPL).

**Comment by ec-mcs** [comment]
This will be part of the new model. So I will close it here.
