### ISSUE TITLE
For more information about the UEA click here not translated.

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#20]
The phrase "For more information about the UEA click here." on page 2 is not translated (page "Welcome to the UEA-Service"), if the language is changed on page 2. It remains in the language which wasselected on the 1st page. (In this case Dutch)
![dutch at second page](https://cloud.githubusercontent.com/assets/19528809/17187396/536a7084-5439-11e6-8b1d-f6b9f3565c4e.JPG)

**Comment by ec-mcs** [comment]
If a user selects on the first page a language, the sentence "For more information...." will stay in this language.

**Comment by ojlaranjo** [comment]
This issue seems to have been solved. If we initially select dutch and then go the next page and there we select english for example, all of the text changes t english like it is supposed to. We can close this now.
