### ISSUE TITLE
Part I A: Type of procedure - translation

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#201]
Missing translation for 
type_of_procedure=Type of procedure
type_of_procedure_none=Not specified
type_of_procedure_open=Open procedure
type_of_procedure_resticted=Restricted procedure
type_of_procedure_negotiation=Competitive procedure with negotiation
type_of_procedure_dialogue=Competitive dialogue
type_of_procedure_partnership=Innovation partnership

**Comment by nfouka** [comment]
Hello ,
I would like to save the Type of procedure but I can not find it on the XML file, could you tell me how to interger it in the XML file?
does the EspdDocument.getTypeProdecure return a non-null value?

**Comment by ec-mcs** [comment]
[Forms_labels_R2.0.9.xlsx](https://github.com/ESPD/ESPD-Service/files/2282292/Forms_labels_R2.0.9.xlsx)

**Comment by ec-mcs** [comment]
Done
