### ISSUE TITLE
Problem answering request xml when nothing is selected by CA

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#22]
When a contracting authority in the tab "selection" checks nothing, and when the  entrepreneur uploads this xml to answer the questions  to see all options from the "selection" tab to fill. Problem lies in the fact that it is not very clear that when you are as contracting authority in the tab "Selection" you have to choose one of  “ɑ: General instructions must select all selection criteria” OR “A, B, C, D underneath”

**Comment by ec-mcs** [comment]
This cannot be solved through software but is a general problem of the ESPD. It might be that the buyer wants the supplier to use the alpha criterion, or maybe from A to D. There are as well cases where the buyer selects the alpha criterion but wants the supplier to provide structured information. As we cannot solve this, I will close this issue.
