### ISSUE TITLE
As entrepreneur reloading xml changes values.

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#23]
If you are an entrepreneur  and leave all or some  yes / no questions blank, then save the XML and then reopen it. Then all unfilled yes / no questions have the value no.

**Comment by ec-mcs** [comment]
For exclusion and selection we will always show the default values. For "information electronically available" will be "no".
For YES/NO on Part II nothing will be selected and if the EO has not answered them an warning will be shown when he clicks on "next"

**Comment by ec-mcs** [comment]
We will only implement this for part II and III
If you are an entrepreneur and leave all or some yes / no questions blank, then save the XML and then reopen it. Then all unfilled yes / no questions have the value no.
