### ISSUE TITLE
field behind URL PB s

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#25]
The field behind URL PB S does not appear to be present. However, if you click on the shaded part (see Annex URL OJ S.jpg) than the same screen opens in a new tab again.
![url pb s](https://cloud.githubusercontent.com/assets/19528809/17187651/71860848-543a-11e6-8b51-7d6f64837073.JPG)

**Comment by ec-mcs** [comment]
When the buyer provides a temporary ID and it is published on TED, the link will be shown. As this is not elegant but not critical and as we want to phase out our service in 2019, I will close this issue.
