### ISSUE TITLE
Select country always in English 

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#26]
On the homepage is the countries field only available in English. ( "Where is your authority located?")
![select country](https://cloud.githubusercontent.com/assets/19528809/17187750/d76ef6ba-543a-11e6-869c-c4dd3f8a1f8d.JPG)

**Comment by ec-mcs** [comment]
This is solved with the latest versions. The countries are translated:
https://github.com/ESPD/ESPD-Service/blob/master/espd-web/src/main/resources/i18n/messages_nl.properties
