### ISSUE TITLE
CA does not tick options but are still listed on print page and request xml

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#29]
When a contracting authority in ESPD  Selection page selects "General instructions for all selection criteria" does not tick this option it still will be displayed in the print list and put in the xml. The question is whether this is intended?

**Comment by ec-mcs** [comment]
I could not find "General instructions for all selection criteria". Does this still apply or can it be closed?

**Comment by ec-mcs** [comment]
We have updated the solution, so this issue should be solved.
