### ISSUE TITLE
View as Entrepreneur options are not correctly shown.

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#30]
Where a contracting authority in ESPD on the Exclusion page options selected at "C: Grounds relating to insolvency, conflict of interest or misconduct" and / or "D: Purely national exclusion grounds" and the link at the top of the page "View (if entrepreneur) "is clicked there are no questions at sections C and D shown. 
 When the" View (as contracting authority) "is clicked, the selected options at C and D are not checked.
![bekijken als ondernemer](https://cloud.githubusercontent.com/assets/19528809/17187973/9e1c2cec-543b-11e6-9c85-4ae1af86459e.jpg)

**Comment by ec-mcs** [comment]
This was solved.
