### ISSUE TITLE
KvK number is filled in for the VAT number after reloading the xml

### ISSUE THREAD

**Issue by kleterpe** [ESPD/ESPD-Service#32]
As an entrepreneur, you can enter a rsinnr or KvKnr in the ESPD. If only the VAT number (rsinnr) is left blank and the KvKnr national number is filled in, then it goes in the first time to fill properly. If you load the answer (XML), then the KvK number is filled in for the VAT number.

**Comment by dg-grow-virgiliu-ratoi** [comment]
it's true, because we use two cac:Party.cac:PartyIdentification elements with no way of telling which one is the VAT number and which one is the national number.

**Comment by dg-grow-virgiliu-ratoi** [comment]
as of this version, the ID element inside the PartyIdentification element makes use of these two 'schemeID' attributes to distinguish between the VAT number and national number: 

- VAT_Number
- National_Number
