### ISSUE TITLE
Duplicate ids of requirement groups

### ISSUE THREAD

**Issue by brhaMercell** [ESPD/ESPD-Service#34]
Id 41dd2e9b-1bfd-44c7-93ee-56bd74a4334b is used for both G2.1 (URL/Code) and G1.1 (Date of conviction/Reason/Who has been convicted).

**Comment by dg-grow-virgiliu-ratoi** [comment]
This affects mainly the criminal convictions exclusion criteria. I will change the ids of all G1.1 groups for these exclusion criteria. The impact should be minimal since the ids of the requirement groups don't have a real business meaning and influence.

**Comment by dg-grow-virgiliu-ratoi** [comment]
The new id for the G1.1 (Date of conviction/Reason/Who has been convicted) group will be 'f5276600-a2b6-4ff6-a90e-b31fe19dae41'.
