### ISSUE TITLE
Consortium name

### ISSUE THREAD

**Issue by tsirafa** [ESPD/ESPD-Service#4]
To introduce the name of the Consortium in the ESPDResponse.

**Comment by tsirafa** [comment]
To all contributors,

Do you know where is the best place to add this information?

Thank you
Fani

**Comment by dg-grow-virgiliu-ratoi** [comment]
It belongs to <xsd:element ref="espd-cbc:EconomicOperatorGroupName" minOccurs="0"/> inside the ESPD Response

**Comment by dg-grow-virgiliu-ratoi** [comment]
It was added in part 2 section C
