### ISSUE TITLE
Issue with TED Standard form 14 - "VII.1.2: instead of" - limited to 1000 characters - should be 4000

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#41]
We have noticed an issue that is not ESPD related but concerns TED. Could you please forward this issue to the right people!

In contract notice one can input in II.2.4 Description of the procurement 4000 characters.

When making corigendum notice, with standard form 14, there is a limitation of 1000 characters in field "VII.1,2 Text to corrected in original notice".

**Could you please increase this limitation to 4000 charecters.**

**Comment by ec-mcs** [comment]
Hi, I forwarded this to the Publications Office. I close this issue as it is not related to the ESPD service. But as you see - it works :-)
