### ISSUE TITLE
Inform users that they are using the wrong environment

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#42]
Currently the acceptance environment does not work because of the update of the new weblogic server. Because in some MS the acceptance environment is used as the production environment users are complaining. We should implement by default a message to ask them using the correct environment.
The message should be in darkred and bold:

> Dear user, you are using our testing environment. Please use https://ec.europa.eu/espd

This should be normally in the code. Could you please apply it as well as hot fix in the acceptance env?

The screenshots below show where the test should be placed.

Thx, MC

![capture2](https://cloud.githubusercontent.com/assets/20335285/17735330/ce6a10d4-6481-11e6-9476-e4fd59318304.PNG)
![capture1](https://cloud.githubusercontent.com/assets/20335285/17735329/ce673a6c-6481-11e6-89d7-93a6f9ac9a02.PNG)

**Comment by dg-grow-alexey-lukashov** [comment]
hotfix applied for acceptance
