### ISSUE TITLE
FI translation: "toimialarekisteri". Part IV: Selection criteria, A: Suitability -> Enrolment in a trade register

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#43]
This is translated in FI as “toimialarekisteriin merkitseminen” (rough translation “recording in sectoral register”).  

We do not have any “sectoral register” – the correct translation should be “kaupparekisteriin merkitseminen” (registering in trade register).

**Comment by ojlaranjo** [comment]
Translation seems to have been corrected. Closing this one now.
