### ISSUE TITLE
FI translation: "se" (=it) not clear to whom "se" (=it) referst to. Part IV Selection Criteria, A: Suitability. 

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#45]
This is an issues of taste but in Finnish it is not clear to whom "it" refers to. I would replace all "se" words with the following suggestion:

Translation suggestion: "tarjoaja..." 

Alternatively "talouden toimija" could be used but this is not used in collocial language. "Talouden toimija" has also other connotations.

![sieppaa](https://cloud.githubusercontent.com/assets/20238848/17765505/dfd0f5f6-652e-11e6-9817-8a87583e72c3.JPG)

**Comment by rantati7** [comment]
![sieppaa](https://cloud.githubusercontent.com/assets/20238848/17765555/3838ca7a-652f-11e6-906f-7399d73b2f24.JPG)

**Comment by ojlaranjo** [comment]
"Se" issue still present.
