### ISSUE TITLE
FI translation: "tutkimusjärjestelmä": Part IV: Selection criteria, C: Technical and professional ability -> Study and research facilities

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#46]
There is a problem with the translation that stems from the translation of the regulation. Study and research facilities is translated as "Tutkimus- ja kehitysjärjestelmät".

Surely  this is not what was meant.. Word facilities is translated as "systems" (järjestelmät).

In FI it is very unclear, while in English it makes sense. 

Translation suggestion: "Tutkimus- ja tuotekehitystoiminnot". Alternatively: "tutkimus- ja tuotekehitystilat / palvelut."

**Comment by ojlaranjo** [comment]
"Tutkimus- ja kehitysjärjestelmät" still present in DEV.
