### ISSUE TITLE
FI translation: "toimitusketjun hallinta": Part IV: Selection criteria, C: Technical and professional ability -> Suppy chain management 

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#47]
Current text in English:

"It will be able to apply the following supply chain management and tracking systems when performing the contract: "

Current text in Finnish:

"Se voi käyttää seuraavia toimitusketjun hallinnointi- ja seurantajärjestelmiä hankintasopimuksen toteuttamisen yhteydessä: "

Suggestions for translation:

"Toimitusketjun hallinta

Tarjoaja / talouden toimija käyttää seuraavia menetelmiä tai järjestelmiä toimitusketjun hallinnoinnissa ja seurannassa.

iä hankintasopimuksen toteuttamisen yhteydessä:

**Comment by ojlaranjo** [comment]
"Se voi käyttää seuraavia toimitusketjun hallinnointi- ja seurantajärjestelmiä hankintasopimuksen toteuttamisen yhteydessä:" is still present in DEV.
