### ISSUE TITLE
FI translations: EO side: missing translation in "Consortium". Part II: Information concerning the economic operator C: Information about reliance on the capacities of other entities

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#49]
this is very difficult part in ESPD.

Nevertheless, consortium is not translated into Finnish. 

Translation suggestions: 

"ryhmittymän nimi"

![sieppaa](https://cloud.githubusercontent.com/assets/20238848/17767335/3f5f27b4-6538-11e6-8ecd-016cafd83d7e.JPG)
iä ja

**Comment by ojlaranjo** [comment]
"Consortium Name" is still present.

**Comment by ojlaranjo** [comment]
Consortium name not present anymore in DEV.
