### ISSUE TITLE
FI translation: General issue: economic operator is collocially translated (elsewhere) as "elinkeinonharjoittaja"

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#50]
This is a general comment to all EC translations In Finnish term "elinkeinonharjoittaja" is more commonly used than "talouden toimija" (economic operator), when referring to companies and businesses operating in the market.

**Comment by ec-mcs** [comment]
Hi Timo, I have received the following comment from our translator
I could not do anything about one comment ("economic operator is colloquially translated (elsewhere) as "elinkeinonharjoittaja") because, well, it is "elsewhere".
