### ISSUE TITLE
FI translation: "Tuensaajat" Part IV, C: Technical and professional ability 

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#53]
There is a translation mistake. "Recipents" is translated as "tuesaajat" (beneficiaries),

In this context this is wrong and should be translated as "vastaanottajat" or even better "tilaaja".

**Comment by rantati7** [comment]
![sieppaa21](https://cloud.githubusercontent.com/assets/20238848/17778022/4f1d6f2a-656b-11e6-9bae-58201389bc85.JPG)

**Comment by rantati7** [comment]
![sieppaa22](https://cloud.githubusercontent.com/assets/20238848/17778078/8de929b0-656b-11e6-8e2c-576eca472da9.JPG)

**Comment by ojlaranjo** [comment]
"Tuensaajat" is still present.
