### ISSUE TITLE
Start page: Chi è a compilare il DGUE?

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#65]
Instead of
Chi è a compilare il DGUE?
Better
Chi è deve compilare il DGUE?

**Comment by pierpa1965** [comment]
Hi Marc, please note that in Italian is better "Chi deve compilare il DGUE?"
Best Regards

**Comment by ojlaranjo** [comment]
Hi Marc were these (and also from other issues) Italian translations corrected in the end? From what I recall everything was fixed. Regards
