### ISSUE TITLE
Part V should not be shown in an open procedure

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#67]
We have received the following comment from PL:
Dzień dobry,
Mam problem z plikiem ESPD w wersji XML, przygotowałem go w postępowaniu dla przetargu nieograniczonego i wygenerowała mi się część V dot. kryteriów selekcji. Nie znalazłem żadnej opcji pozwalającej pominąć tę część formularza ani nie jest ona widoczna w trakcie przygotowywania formularza, dopiero na etapie jego wypełniania jako wykonawca lub po wyeksportowaniu do pliku. ESPD próbowałem wygenerować zarówno z podaniem numeru ogłoszenia, jak i bez, ale efekt był ten sam.
Część V w przetargu nieograniczonym jest zbędna i może wprowadzać w błąd wykonawców.
Czy można wygenerować formularz bez tej części, ew. czy coś źle przygotowałem w załączonym pliku?

**Google translate:**
Good morning,
I have a problem with the file ESPD version of XML, I prepared it in the proceedings for an open tender and generated my part V dot. Selection criteria. I have not found any option that allows to skip this part of the form, or it is not visible during the preparation of the form, only at the stage of its fulfillment as a performer or exported to a file. ESPD tried to generate both quoting the announcement and without, but the effect was the same.
Part V in the open tender is unnecessary and may be misleading contractors.
Is it possible to generate form without this part, if necessary. Or something badly prepared in the attached file?

**Solution**
The best solution would be to have the possibility to provide the type of procedure in "Part I". The list would be (taken from the contract notice http://simap.ted.europa.eu/documents/10184/99173/EN_F02.pdf:

Type of procedure
- Not specified (because it may not be selected)
- Open procedure
- Restricted procedure -> Part V will be shown
- Competitive procedure with negotiation -> Part V will be shown
- Competitive dialogue -> Part V will be shown
- Innovation partnership -> Part V will be shown

As we can retrieve certain information from the Publications Office, this should be added so that it fills automatically.

![capture](https://cloud.githubusercontent.com/assets/20335285/17802593/621c3224-65f1-11e6-9474-491ee54ad38c.PNG)

**Comment by maierankoe** [comment]
There should be the possibility to select an ESPD for an open procedure. In this ESPD the Selection Criteria should not be shown.
In an open procedure the term "Selection Criteria" by itself might easily cause confusion with the Contracting Authority and the Economic Operators.

**Comment by sakispantazis** [comment]
As it stands, the form creates confusion as to how exactly the EO’s should deal with this particular field when filling out the ESPD for contracts that are not restricted (i.e. : open procedures). Why not keeping  Part V and add between the info text and the economic operator's declaration (two) additional radio buttons with options, for example "Not Applicable" and "Candidates Reduction".
Only in the case of "Candidates Reduction" the section with the economic operators declaration should be visible.

**Comment by ec-mcs** [comment]
This is seen as important to reduce confusion on the side of EO. We should request to receive information about the procedure type from OP.

**Comment by dariuszwojcicki** [comment]
For the January rel. will add the list not stored in xml file, for Easern rel. will add to the xml file.

**Comment by ec-mcs** [comment]
The same codes as the one used for CNs should be used.
The procedure type should be handed over as HTTPPOST as well

**Comment by hildekjol** [comment]
I agree on this issue. We get a lot of questions from EOs regarding this, even though we have tried to clarify it in the information text.

The best solution would be that CA may choose to omit part V, either by radio buttons ('Candidates reduction' or 'No candidates reduction') or by choosing type of procedure. The latter is probably better as for statistics, but the first is less complicated.
