### ISSUE TITLE
Problem with unique identifiers in ESPD response file. 

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#68]
Attached screenshot is from ESPD-Response. In this example you need three guids (ids) to identify criterion because they aren’t unique. It would be much easier if each criterion had unique identifier.

Where can we find those Guids so that we can use them in our system to identify criteria when exporting/importing profiles?
![espd-response](https://cloud.githubusercontent.com/assets/20238848/17802805/0539d110-65fb-11e6-9c1d-a8a6b6dba711.png)

**Comment by dg-grow-virgiliu-ratoi** [comment]
the criteria are defined at this location in the source code of the ESPD Service: [https://github.com/ESPD/ESPD-Service/tree/master/espd-web/src/main/resources/criteria](url). there you will find 3 JSON files.

or in the ESPD Data Model here: [https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/code_lists/xls/CriteriaTaxonomy.xlsx](url)

**Comment by ec-mcs** [comment]
Done
