### ISSUE TITLE
Data is lost when navigation through menu

### ISSUE THREAD

**Issue by Chanderbhan** [ESPD/ESPD-Service#69]
![bug espd - 1](https://cloud.githubusercontent.com/assets/17125196/17809561/cd6384b2-6617-11e6-9c5b-afefba6e7069.JPG)
![bug espd - 2](https://cloud.githubusercontent.com/assets/17125196/17809562/cd640ab8-6617-11e6-9818-1d07e604dba1.JPG)
![bug espd - 3](https://cloud.githubusercontent.com/assets/17125196/17809563/cd65225e-6617-11e6-8978-211e7f5a5f41.JPG)

Data is lost when navigation through menu balk instead of using the buttons Next and Previous below.

If you fill in fields or checkboxes checked on / off , then do not click on the Next button, but use the menu balk at the top to navigate to the next page, then your changes  disappears when you return back to the page.

Steps:
Step 1: I fill in information on Procedure.
Step 2: I click Exclusions via menu balk.
Step 3: I go back to Procedure and see the completed data is gone.

**Comment by dg-grow-virgiliu-ratoi** [comment]
this is normal from a technical point of view but abnormal for users. the next and previous buttons have the purpose of submitting the data to the server while the navigational links are currently supposed to just take you from one page to another.

**Comment by Chanderbhan** [comment]
In that case and if possible to make the navigational links not clickable by the user.

Van: Virgiliu Ratoi [mailto:notifications@github.com]
Verzonden: vrijdag 19 augustus 2016 16:19
Aan: ESPD/ESPD-Service
CC: Khoenkhoen, C. (Chander); Author
Onderwerp: Re: [ESPD/ESPD-Service] Data is lost when navigation through menu (#69)


this is normal from a technical point of view but abnormal for users. the next and previous buttons have the purpose of submitting the data to the server while the navigational links are currently supposed to just take you from one page to another.

**Comment by ec-mcs** [comment]
As we will phase out, we will not touch this as it would require some reprogramming.
