### ISSUE TITLE
Versioning of XML implementation

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#73]
We have to change the XML sometimes. In order to keept track we need to add a version number for example 1.0.1.~~4~~ (1.0.1 is the XSD, 4 is the XML)

**Comment by paulakeen** [comment]
Point taken. This will be also taken into account when implementing the transformation between XML reversioned instances.

**Comment by ESPD** [comment]
Versioning 1.0.1.4.2016.12

**Comment by ESPD** [comment]
Versioning of XML through versioning of ESPD service like 2016.12.01 (year.month.minor-release). In this way we do not have to maintain an artificial number.

**Comment by Renper** [comment]
Hi
We agree on that we need a way of understanding the XML version, then every time the XML is updated, it may affect XML transformation, UI or validation
How are you planning to that? 
What element will be used for that purpose?
We have seen that the element “cbc:VersionID” contains a version number in format (year.month.day). Is this the element that will be use to tag/provide the XML version? Can you please confirm?

**Comment by ec-mcs** [comment]
We will close it due to aging...
