### ISSUE TITLE
Wrong default currency for the  Netherlands (ANG instead of Euro)

### ISSUE THREAD

**Issue by Chanderbhan** [ESPD/ESPD-Service#77]
In the July / August release of the ESPD a couple of things differently than before.

In the ESPD now  a standard currency is selected on the basis of the country where the EO/CA is located. For the Netherlands the Netherlands Antillean guilder (ANG Netherlands Antillean Guilder =) is chosen instead of the Euro.

**Comment by hofdesir** [comment]
When using the new code from currencies.jsp a bug occurs, it has something to do with this code:
"selected="${espd.economicOperator.country.currency == curr ? 'selected' : ''}"

1. when loading a page that contains a dropdown with currencies, the default currency will be set depending on the country that is selected.
2. The user changes this currency into the same currency (example: old value is EURO, new value is EURO) 

The html tag for the selected currency gets two attributes with selected="selected", which makes the HTML invalid:

		**<option data-i18n="currency_EUR" selected="selected" value="EUR" selected="selected">
			EUR (Euro)
		</option>**

For the PDF rendering that we have made for TenderNed,  we need valid HTML to transform it.

**Comment by Robert-Smit** [comment]
diff --git a/espd-web/src/main/java/eu/europa/ec/grow/espd/domain/enums/other/Country.java b/espd-web/src/main/java/eu/europa/ec/grow/espd/domain/enums/other/Country.java
index 3213dca..f9ae46a 100644
--- a/espd-web/src/main/java/eu/europa/ec/grow/espd/domain/enums/other/Country.java
+++ b/espd-web/src/main/java/eu/europa/ec/grow/espd/domain/enums/other/Country.java
@@ -203,7 +203,7 @@ public enum Country implements CacCountry {
 	NF("NF", "Norfolk Island", Currency.AUD),
 	NG("NG", "Nigeria", Currency.NGN),
 	NI("NI", "Nicaragua", Currency.NIO),
-	NL("NL", "Netherlands", Currency.ANG),
+	NL("NL", "Netherlands", Currency.EUR),
 	NO("NO", "Norway", Currency.NOK),
 	NP("NP", "Nepal", Currency.INR),
 	NR("NR", "Nauru", Currency.AUD),

**Comment by dg-grow-virgiliu-ratoi** [comment]
@hofdesir Your comment is very useful, however it applies to this Github issue: #80

**Comment by Chanderbhan** [comment]
Ok.
Please, the issues are not slightly different.
I leaf it up to you.

Regards,
Chander



Van: Virgiliu Ratoi [mailto:notifications@github.com]
Verzonden: vrijdag 23 september 2016 10:22
Aan: ESPD/ESPD-Service
CC: Khoenkhoen, C. (Chander); Author
Onderwerp: Re: [ESPD/ESPD-Service] Wrong default currency for the Netherlands (ANG instead of Euro) (#77)


@hofdesir<https://github.com/hofdesir> Your comment is very useful, however it applies to this Github issue: #80<https://github.com/ESPD/ESPD-Service/issues/80>
