### ISSUE TITLE
If ESPD service receives an empty response from TED, the answer should be ignored.

### ISSUE THREAD

**Issue by ojlaranjo** [ESPD/ESPD-Service#83]
The fields that are filled out by the CA will be overwritten with the response retrieved from TED, even if the response is empty. (see attachment)

[espd-request (6).zip](https://github.com/ESPD/ESPD-Service/files/461611/espd-request.6.zip)

Solution: if the response is empty, answer should be ignored.

**Comment by dg-grow-virgiliu-ratoi** [comment]
This scenario can occur in the following situations
- the temporary id filled in by the user is invalid in which case we receive a bad request from TED
- the credentials which we use for TED are incorrect or expired
- other unforeseen errors
Nevertheless, if the TED response is empty we will not override the procurement information any more.
