### ISSUE TITLE
Part III D: Purely national exlclusion grounds are allowing for self-cleaning

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#86]
In the current version the ESPD service does not allow for self-cleaning measures for purely national exclusion grounds. This must be added. I guess this has an impact on the XML. If this is the case, it should be solved with our December release.
![capture1](https://cloud.githubusercontent.com/assets/20335285/18703014/78899e86-7fe4-11e6-8253-a14db4140c95.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20335285/18703013/7888cf10-7fe4-11e6-90e5-42acdba863a0.PNG)

**Comment by ivanholic** [comment]
Economic operators would also welcome the direct description of national grounds in the ESPD. Is it possible to include the relevant box providing the space for contracting authorities to describe such grounds in the ESPD service (e.g. if CA ticks YES, national grounds will apply)? 

![national grounds](https://cloud.githubusercontent.com/assets/22398053/18792195/ccb334ea-81b5-11e6-925f-e8a3d3ea5ebd.png)

Same principle as in the role "Econmic operator" would be sufficient (picture in the previous comment)
Thx.
