### ISSUE TITLE
Part III D: Purely national exclusion grounds wording should be changed

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#87]
The text is currently not clear what the EO should click. Therefore it should be changed from:
Other exclusion grounds that may be foreseen in the national legislation of the contracting authority's or contracting entity's Member State. Do the purely national grounds of exclusion, which are specified in the relevant notice or in the procurement documents, apply?
To:
Other exclusion grounds that may be foreseen in the national legislation of the contracting authority's or contracting entity's Member State. **Has the economic operator breached its obligations relating to** the purely national grounds of exclusion, which are specified in the relevant notice or in the procurement documents?

**Comment by ojlaranjo** [comment]
Still not corrected in DEV.

**Comment by ec-mcs** [comment]
Voted in favour
