### ISSUE TITLE
Contracting entities should be able to deselect exclusion grounds

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#88]
The contracting entities have the possibility to deselect exclusion grounds. Therefore we need to add one category in "Who are you?"
- I am a contracting authority (i - The term contracting authority refers to the buyer.)
- I am a contracting entity (i - The term contracting entity refers here to a buyer which operates in the water, energy, transport or postal services sector. For contracting authorities who are also operating in the sectors mentioned before have to select "I am a contracting authority")
- I am an economic operator (i - The term economic operator refers to the supplier / bidder.)

We should include this in the schematron file if possible. 
![capture](https://cloud.githubusercontent.com/assets/20335285/18703269/7b80d482-7fe5-11e6-9b96-825f8a8e740a.PNG)

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on development
