### ISSUE TITLE
Part I: Addition of a national reference number

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#89]
From BG: 
In Part I "Information for the publication" a field is missing in which to be indicated a reference to a number of a publication at national level.

We should provide the possibility to add a national reference number because that would help companies in a country to identify it on a  national portal.

We have to check if this has an impact on the current data model or not.

**Comment by ec-mcs** [comment]
Where shall we store the national reference number?

**Comment by ec-mcs** [comment]
We could add this in the March (Easter Egg Release). It is needed by NL.

**Comment by paulakeen** [comment]
This has been discussed with the MSs. Please find below the final decision:

https://github.com/ESPD/ESPD-EDM/wiki/6.-Information-about-publication

**Comment by dg-grow-roberto-vormittag** [comment]
The change described by paulakeen will be implemented in version 2.0
