### ISSUE TITLE
Allow for references "start date" and "end date"

### ISSUE THREAD

**Issue by tsirafa** [ESPD/ESPD-Service#9]

**Comment by tsirafa** [comment]
Enric was suggesting to define not only start date and end date, but in certain cases, e.g. Spain, they use only start date plus a duration e.g. 5 months. We should definitely take this into consideration and we should support all of these options.

**Comment by dg-grow-virgiliu-ratoi** [comment]
It applies to the following section C selection criteria:

- For works contracts: performance of works of the specified type;
- For supply contracts: performance of deliveries of the specified type;
- For service contracts: performance of services of the specified type.
