### ISSUE TITLE
Part II: Concerning the information on registration

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#90]
From BG:
In Part II Concerning the information on registration of the economic operator in official lists of approved economic operators or whether there is an equivalent certificate - in letter "a" according to the regulation it is required indication of the name of the list or the certificate. This is not provided for in the electronic form of the model.

We must change it from
a) Please provide the relevant registration or certification number, if applicable:
To
a) Please provide the name of the list or certificate and the relevant registration or certification number, if applicable:

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on DEV
