### ISSUE TITLE
Printing ESPD: Part II is missing in the print

### ISSUE THREAD

**Issue by maierankoe** [ESPD/ESPD-Service#93]
The User (Contracting Authority) filled in his part of the online form, printed the whole form out, scanned it and added it to the tender documents which are available to the Economic Operators. This was working up until now.
As this user just now stated (30.9.2016, 12:00) this is not possible anymore as Part II, which concerns the Economic Operator, is missing in the printout.
The user also said that it would bei good, that changes in the ESPD Service are announced.
There should be a possibility for a complete print out.
Until the ESPD is integrated in databases and procurement Systems Contracting Authorities will want to use ESPD in printed form.

**Comment by ec-mcs** [comment]
is solved #79 can be closed
