### ISSUE TITLE
Part I: Box of publication should only be shown when published

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#94]
Currently the box on the publication is irritating CAs because the notice is not published but and therefore the fields are empty. Possibly a question should be shown like:
![untitled](https://cloud.githubusercontent.com/assets/20335285/19147227/757dbae0-8bb7-11e6-8838-47eefff42cef.png)

**Comment by rantati7** [comment]
Indeed, this created some hassle. 

When doing ESPD in the Commission ESPD service the contract notice is nearly never already published. Contract notice will be published only after CA makes the XML-file in the ESPD service. 

MCs proposal would be a good addition.

**Comment by ec-mcs** [comment]
After discussion, this field (grey area) should not be shown to the CA because the number will not be available at this time. It should be shown to EOs and in the review functionality. We need to look what we do with the temporary ID that is currently shown in this section.

**Comment by ec-mcs** [comment]
We will leave it as it is and not update our solution anymore.
