### ISSUE TITLE
Webservice interface of the ESPD service

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#95]
TenderNed added a webservice to the ESPD service which allows the possibility to pass parameters to the ESPD service and do the import/export functionality directly without involving manual intervention.
This feature would provide the possibility to offer one ESPD service in a MS and other services could reuse it without any difficulties.

**Comment by dg-grow-virgiliu-ratoi** [comment]
this should already be possible via the current POST requests. we have additional features coming from tenderned to include inside the ESPD service.
