### ISSUE TITLE
Transition from version 1.02 -> 1.1

### ISSUE THREAD

**Issue by rantati7** [ESPD/ESPD-Service#98]
For the ESPD service it would be good if the v. 1.02 and v. 1.1 would co-exist on Commission website at least for 3 months.

If CA has included XML with v.1.02 in their invitation to tender, EO would use old 1.02 version when filling in XML-file.

**Comment by ec-mcs** [comment]
I see your point. We would implement it like this that there might be actually two services running in parallel. It could be even longer if needed. Depending on the version of the XML we would use it in exactly this version.

**Comment by rantati7** [comment]
Normally, the time for submitting bids is below 3 months. Only very seldom it is longer. When it is longer the CA can always submit a new ESPD file to EOs or upload a new one along with Q&A.

**Comment by ec-mcs** [comment]
As we have no plans for updating our ESPD service to v2 I will close this issue.
