### ISSUE TITLE
ENG-SWE: error in translation.

### ISSUE THREAD

**Issue by Makhfi** [ESPD/ESPD-Service#99]
In the Swedish translation of “breached”, the meaning is more or less the opposite, meaning “fulfilled”. Quite confusing.
![capture](https://cloud.githubusercontent.com/assets/22028795/19435103/3be6adc2-9469-11e6-9869-7543061cc468.PNG)

**Comment by ojlaranjo** [comment]
Not sure what word in swedish is the translation for "breached". A swedish speaker could be useful for this one.

**Comment by ec-mcs** [comment]
Solved
